### ISSUE TITLE
void or1k_interrupt_enable(int line) does not work

### ISSUE THREAD

**Issue by minjiexm** [openrisc/newlib#18]
hi, Dear experts:

I am trying to use void or1k_interrupt_enable(int line)  to enable just one interrupt.
But it does not work.
I have to use void or1k_interrupts_enable(void) to enable all interrupts.

Looking forward to your reply.

Thanks.

**Comment by wallento** [comment]
Hi,

IIRC you have to do both, the naming is just a bit confusing. With the first call you set the mask, with the second you then enable interrupts in general.

Cheers,
Stefan
