### ISSUE TITLE
what does it indicate whether it says its installed or is this an error?

### ISSUE THREAD

**Issue by bhatmahadev6** [openrisc/newlib#20]
i did ./configure and make then make install its showing like this...>
make[1]: Entering directory '/home/mahadev/or1k/newlib'
/bin/bash ./mkinstalldirs /usr/local /usr/local
make[2]: Entering directory '/home/mahadev/or1k/newlib/etc'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/mahadev/or1k/newlib/etc'
make[1]: Nothing to be done for 'install-target'.
make[1]: Leaving directory '/home/mahadev/or1k/newlib'

**Comment by jeremybennett** [comment]
General questions like this are best directed to the OpenRISC mailing list at librecores.org (https://lists.librecores.org/listinfo/openrisc). You should include the complete set of commands you issued and attach the log file to your question.
